# Generated by Django 4.1.5 on 2023-01-24 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='affiliate',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='qualifications',
            field=models.TextField(default='Masters Biology'),
            preserve_default=False,
        ),
    ]
