# Generated by Django 4.1.5 on 2023-01-24 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_affiliate_customuser_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.URLField(default='https://i.postimg.cc/rm82XhCm/default-profile-image.png'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='affiliate',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='qualifications',
            field=models.TextField(default=None),
        ),
    ]
