# Generated by Django 4.1.5 on 2023-01-21 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='categories',
            field=models.CharField(choices=[('Engineering', 'Engineering'), ('Chemistry', 'Chemistry')], max_length=200, null=True),
        ),
    ]
