# Generated by Django 4.1.5 on 2023-01-24 04:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0004_alter_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='innovation_star',
            field=models.ManyToManyField(related_name='innovation_star_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='project_email',
            field=models.EmailField(default='project@project.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='question_one',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='question_three',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='question_two',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
