# Generated by Django 4.1.5 on 2023-01-28 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_project_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Eng', 'Engineering'), ('Chem', 'Chemistry'), ('Bio', 'Biology'), ('Math', 'Mathematics'), ('Social Sci', 'Social Sciences'), ('Ecom', 'Economic'), ('Data Sc', 'Data Science'), ('Comp Sci', 'Computer Science'), ('Ecology', 'Ecology'), ('Physics', 'Physics'), ('Materials Sc', 'Material Science'), ('Earth Sci', 'Earth Science'), ('Edu', 'Education'), ('Paleo', 'Paleontology'), ('Med', 'Medicine'), ('Neuro', 'Neuroscience'), ('Psych', 'Pschycology'), ('Anthropology', 'Anthropology'), ('Art and Design', 'Art and Design'), ('Political Sc', 'Political Science'), ('Astro', 'Astrophysics')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 27, 19, 36, 7, 533969)),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.URLField(default='https://i.postimg.cc/pLgqMZxh/test-g95215e4ee-1280.jpg'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
